# Generated by Django 4.2.6 on 2023-10-20 01:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [('main', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fullname', models.CharField(max_length=128)),
                ('phone_country_code', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=128)),
                ('whatsapp_country_code', models.CharField(blank=True, max_length=128, null=True)),
                ('whatsapp_number', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=128)),
                (
                    'education_level',
                    models.CharField(
                        choices=[
                            ('8', '8th grade'),
                            ('9', '9th grade'),
                            ('10', '10th grade'),
                            ('+1', '+1'),
                            ('+2', '+2'),
                            ('other', 'Other'),
                        ],
                        max_length=128,
                    ),
                ),
                ('current_course', models.CharField(blank=True, max_length=128, null=True)),
                ('place', models.CharField(max_length=128)),
                (
                    'unit',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.unit'
                    ),
                ),
            ],
            options={'verbose_name_plural': 'Registrations', 'ordering': ('-date_added',)},
        )
    ]
